resource_group_name  = "test-rg"
location             = "East US"
storage_account_name = "saanvikittestsa"
tags = {
  Environment = "test"
  Project     = "Terraform"
}
subscription_id         = "2e28c82c-17d7-4303-b27a-4141b3d4088f"
virtual_network_name    = "test-vnet"
virtual_network_address = ["10.0.1.0/24"]
subnet_name             = "test-subnet"
subnet_address          = ["10.0.1.0/24"]
public_ip_name          = "test-public-ip"
nic_name                = "test-nic"
nsg_name                = "test-nsg"
virtual_machine_name    = "test-vm"
virtual_machine_size    = "Standard_DS1_v2"
admin_username          = "azureuser"
admin_password          = "P@ssw0rd1234!"